[Writable]
LogLevel = 'DEBUG'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
ClientMonitor = 15000
Host ='172.26.240.14'
ServerBindAddr=''
Port = 49992
Protocol = 'http'
StartupMsg = 'device test started'
Timeout = 20000
ConnectRetries = 20
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = '172.26.240.14'
Port = 8500
Type = 'consul'

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = '172.26.240.14'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = '172.26.240.14'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = '172.26.240.14'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false
  [Device.Discovery]
    Enabled = false
    Interval = '30s'

# Remote and file logging disabled so only stdout logging is used
[Logging]
EnableRemote = false
File = ''

# Pre-define Devices
[[DeviceList]]
  Name = 'Test-Device01'
  Profile = 'Test-Device'
  Description = 'Example of Test Device'
  Labels = [ 'industrial' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
      Address = 'test01'
      Port = '300'
  [[DeviceList.AutoEvents]]
    Frequency = '10s'
    OnChange =false 
    Resource = 'Switch'
  [[DeviceList.AutoEvents]]
    Frequency = '33s'
    OnChange = false
    Resource = 'Image'
